// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAldGTaEE_dIwnL0h4ZxXmRoeETOQdsi0Y',
    appId: '1:1087192546884:android:e2dbe55bcff91ab848c611',
    messagingSenderId: '1087192546884',
    projectId: 'app-dev-d0329',
    storageBucket: 'app-dev-d0329.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3KxzVsSauSICP8_q28W0T0W6izZgn6F0',
    appId: '1:1087192546884:ios:d5f6b8830f3b8b6e48c611',
    messagingSenderId: '1087192546884',
    projectId: 'app-dev-d0329',
    storageBucket: 'app-dev-d0329.appspot.com',
    androidClientId: '1087192546884-g38iljtms1bp9v5gs5ku1d3ttd9coqh6.apps.googleusercontent.com',
    iosClientId: '1087192546884-5vfsdq4qti83ndlpvclb5uuenoch4kob.apps.googleusercontent.com',
    iosBundleId: 'com.example.electrionicProject',
  );
}
